/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.git;

import javax.swing.JOptionPane;

/**
 *
 * @author lapi
 */
public class GUI extends javax.swing.JFrame {

    private SLL issueList = new SLL();
    private MyQueue issueQueue = new MyQueue();
    private MyStack history = new MyStack();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    
    public void showHistory(){
    
       StringBuilder sb = new StringBuilder();

        sb.append("ISSUE LIST \n");
        sb.append(issueList.toDisplayString()).append("\n");

        sb.append(" QUEUE \n");
        sb.append(issueQueue.toString());
        sb.append("\n");

        sb.append("HISTORY \n");
        sb.append(history.toString());

        TextArea.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertIssue = new javax.swing.JButton();
        ShowIssues = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        DoneBtn = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InsertIssue.setText("Insert Issue");
        InsertIssue.addActionListener(this::InsertIssueActionPerformed);

        ShowIssues.setText("Display Issues");
        ShowIssues.addActionListener(this::ShowIssuesActionPerformed);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jLabel1.setText("Current Issues");

        DoneBtn.setText("Mark as done");
        DoneBtn.addActionListener(this::DoneBtnActionPerformed);

        Delete.setText("Delete");
        Delete.addActionListener(this::DeleteActionPerformed);

        Next.setText("Process Next");
        Next.addActionListener(this::NextActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Next)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InsertIssue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShowIssues)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DoneBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowIssues)
                    .addComponent(Delete)
                    .addComponent(DoneBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Next)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertIssueActionPerformed
        // TODO add your handling code here:
       
      
        String input = JOptionPane.showInputDialog(this, "Enter Issue Name (Please insert 'transport' if a transport issue) ");

        if (input == null || input.trim().isEmpty()) {
            return;
        }

        Issues newIssue;
        if (input.toLowerCase().contains("transport")) {
            newIssue = new TransportIssue(input);
        } else {
            newIssue = new Issues(input);
        }

        issueList.addLast(newIssue);

        issueQueue.enqueue(newIssue);
        history.push("Added Issued ID " + newIssue.getID());

           showHistory();

    }//GEN-LAST:event_InsertIssueActionPerformed

    private void ShowIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowIssuesActionPerformed
        // TODO add your handling code here:
       

        showHistory();

    }//GEN-LAST:event_ShowIssuesActionPerformed

    private void DoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneBtnActionPerformed
        // TODO add your handling code here:
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter Issue ID to mark as done:");

    if (input == null || input.trim().isEmpty()) {
        return;
    }

    try {
        int id = Integer.parseInt(input);
        boolean updated = issueList.updateIssueStatus(id, "done");

        if (updated) {
            issueQueue.removeById(id);
            history.push("Marked issue ID " + id + " as done");
            javax.swing.JOptionPane.showMessageDialog(this, "Issue marked as done.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Issue ID not found.");
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number.");
    }
        
        showHistory();
    }//GEN-LAST:event_DoneBtnActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Enter Issue ID to delete:");
        if (input == null || input.trim().isEmpty()) {
            return;
        }

        try {
            int id = Integer.parseInt(input);
            boolean deleted = issueList.deleteById(id);

            if (deleted) {
                issueQueue.removeById(id);
                history.push("Deleted issue ID " + id);
                JOptionPane.showMessageDialog(this, "Issue deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Issue ID not found.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number.");
        }
        showHistory();
    }//GEN-LAST:event_DeleteActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        Issues nextIssue = (Issues) issueQueue.dequeue();

        if (nextIssue == null) {
            JOptionPane.showMessageDialog(this, "No issues in queue.");
            return;
        }

        issueList.deleteById(nextIssue.getID());
        history.push("Processed issue ID " + nextIssue.getID());

          showHistory();

        JOptionPane.showMessageDialog(this,
                "Processed: " + nextIssue.toString());
    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton DoneBtn;
    private javax.swing.JButton InsertIssue;
    private javax.swing.JButton Next;
    private javax.swing.JButton ShowIssues;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
