/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.git;

/**
 *
 * @author lapi
 */
public class GUI extends javax.swing.JFrame {
     private SLL issueList = new SLL();
     private MyQueue issueQueue = new MyQueue();
     private MyStack history = new MyStack();

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertIssue = new javax.swing.JButton();
        ShowIssues = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        IssueName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InsertIssue.setText("Insert Issue");
        InsertIssue.addActionListener(this::InsertIssueActionPerformed);

        ShowIssues.setText("Display Issues");
        ShowIssues.addActionListener(this::ShowIssuesActionPerformed);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jLabel1.setText("Current Issues");

        IssueName.addActionListener(this::IssueNameActionPerformed);

        jLabel2.setText("Issue Name");

        Delete.setText("Mark as done");
        Delete.addActionListener(this::DeleteActionPerformed);

        jButton1.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(IssueName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(InsertIssue)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ShowIssues))
                        .addComponent(jScrollPane1)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IssueName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowIssues))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete)
                    .addComponent(jButton1))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertIssueActionPerformed
        // TODO add your handling code here:
        Issues newIssue;
    String issueName = IssueName.getText();
        if(issueName.toLowerCase().contains("traffic")){
            issueName = "Funziona";
            newIssue = new TransportIssue(issueName);
            
        }
        else{
            newIssue = new Issues(issueName);
        }
        
        issueList.addLast(newIssue);
        IssueName.setText("");
        
        issueQueue.enqueue(newIssue);
        history.push("Added Issued ID "+newIssue.getID());
    }//GEN-LAST:event_InsertIssueActionPerformed

    private void ShowIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowIssuesActionPerformed
        // TODO add your handling code here:
         StringBuilder sb = new StringBuilder();

    sb.append("ISSUE LIST \n");
    sb.append(issueList.toDisplayString()).append("\n");

    sb.append(" QUEUE \n");
    sb.append(issueQueue.toString());
    
    sb.append("History \n");
    sb.append(history.toString());

    TextArea.setText(sb.toString());
    
    }//GEN-LAST:event_ShowIssuesActionPerformed

    private void IssueNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueNameActionPerformed
        // TODO add your handling code here:
        IssueName.setText("");
    }//GEN-LAST:event_IssueNameActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter Issue ID to mark as done:");

    if (input == null || input.trim().isEmpty()) {
        return;
    }

    try {
        int id = Integer.parseInt(input);
        boolean updated = issueList.updateIssueStatus(id, "done");
        
        if (updated) {
            history.push("Marked issue ID " + id + " as done");
            issueList.deleteById(id);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Issue updated successfully.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Issue ID not found.");
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number.");
    }
   
    TextArea.setText(history.toString());
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton InsertIssue;
    private javax.swing.JTextField IssueName;
    private javax.swing.JButton ShowIssues;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
